import "@tanstack/react-start/server-only";

import { randomUUID } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";

import type { StorageDriver, StoredFile } from "./types";

/**
 * Development/local storage driver. Files live outside the public web
 * root, under a directory this process fully controls
 * (`MEDICAL_UPLOAD_DIR`, default `./private-uploads`), and are only ever
 * reachable through `src/lib/documents/functions.ts`'s authenticated
 * download function — never through a static file server or a guessable
 * URL.
 *
 * Storage keys are random UUIDs, generated here, never derived from a
 * caller-supplied filename or path. `resolveSafePath` re-derives the path
 * from the key and asserts the result is still inside the storage root
 * before touching the filesystem, which is what actually prevents path
 * traversal — sanitizing the *input* isn't enough on its own.
 */
export class LocalStorageDriver implements StorageDriver {
  private readonly root: string;
  private ensured: Promise<void> | null = null;

  constructor(root?: string) {
    this.root = path.resolve(root ?? process.env["MEDICAL_UPLOAD_DIR"] ?? "./private-uploads");
  }

  private async ensureRoot(): Promise<void> {
    if (!this.ensured) {
      this.ensured = fs.mkdir(this.root, { recursive: true }).then(() => undefined);
    }
    await this.ensured;
  }

  /**
   * Turns a storage key into an absolute path and verifies it's still
   * inside `this.root`. This is the actual path-traversal defense — even
   * if a malformed/malicious key ever reached this function, the resolved
   * path is checked against the root before any filesystem call.
   */
  private resolveSafePath(key: string): string {
    // Keys are generated by this class only (see `put`), but this function
    // is defense in depth: it never trusts that invariant blindly.
    const safeKey = path.basename(key);
    const resolved = path.resolve(this.root, safeKey);
    const rootWithSep = this.root.endsWith(path.sep) ? this.root : this.root + path.sep;
    if (resolved !== this.root && !resolved.startsWith(rootWithSep)) {
      throw new Error("Refusing to resolve a storage key outside the storage root.");
    }
    return resolved;
  }

  async put(data: Buffer): Promise<StoredFile> {
    await this.ensureRoot();
    // Random key, unrelated to any filename the client sent — the display
    // name is stored separately as metadata (`originalFilename` in the DB).
    const key = randomUUID();
    const target = this.resolveSafePath(key);
    await fs.writeFile(target, data, { mode: 0o600 });
    return { key, size: data.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    const target = this.resolveSafePath(key);
    return fs.readFile(target);
  }

  async delete(key: string): Promise<void> {
    const target = this.resolveSafePath(key);
    try {
      await fs.unlink(target);
    } catch (error) {
      // Best-effort cleanup only — a missing file is not itself an error
      // the caller needs to see (see service.server.ts's rollback path).
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  }
}
