import "@tanstack/react-start/server-only";

import { createHash, createHmac, randomUUID } from "node:crypto";

import type { StorageDriver, StoredFile } from "./types";

interface R2Config {
  endpoint: URL;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
}

function required(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required when STORAGE_DRIVER=r2.`);
  return value;
}

function loadConfig(): R2Config {
  const endpoint = new URL(required("R2_ENDPOINT"));
  if (endpoint.protocol !== "https:") throw new Error("R2_ENDPOINT must use https://.");
  endpoint.pathname = endpoint.pathname.replace(/\/+$/, "");
  return {
    endpoint,
    bucket: required("R2_BUCKET"),
    accessKeyId: required("R2_ACCESS_KEY_ID"),
    secretAccessKey: required("R2_SECRET_ACCESS_KEY"),
  };
}

function sha256(value: Buffer | string): string {
  return createHash("sha256").update(value).digest("hex");
}

function hmac(key: Buffer | string, value: string): Buffer {
  return createHmac("sha256", key).update(value).digest();
}

function encodePathPart(value: string): string {
  return encodeURIComponent(value).replace(
    /[!'()*]/g,
    (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`,
  );
}

function signingKey(secret: string, date: string): Buffer {
  const kDate = hmac(`AWS4${secret}`, date);
  const kRegion = hmac(kDate, "auto");
  const kService = hmac(kRegion, "s3");
  return hmac(kService, "aws4_request");
}

export class R2StorageDriver implements StorageDriver {
  private readonly config = loadConfig();

  private objectUrl(key: string): URL {
    // Keys are generated by this driver, but encode every segment anyway.
    const url = new URL(this.config.endpoint.toString());
    const base = url.pathname.replace(/\/+$/, "");
    url.pathname = `${base}/${encodePathPart(this.config.bucket)}/${encodePathPart(key)}`;
    return url;
  }

  private async request(
    method: "GET" | "PUT" | "DELETE",
    key: string,
    body?: Buffer,
  ): Promise<Response> {
    const url = this.objectUrl(key);
    const now = new Date();
    const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, "");
    const shortDate = amzDate.slice(0, 8);
    const payloadHash = sha256(body ?? Buffer.alloc(0));
    const canonicalHeaders = `host:${url.host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${amzDate}\n`;
    const signedHeaders = "host;x-amz-content-sha256;x-amz-date";
    const canonicalRequest = [
      method,
      url.pathname,
      "",
      canonicalHeaders,
      signedHeaders,
      payloadHash,
    ].join("\n");
    const scope = `${shortDate}/auto/s3/aws4_request`;
    const stringToSign = ["AWS4-HMAC-SHA256", amzDate, scope, sha256(canonicalRequest)].join("\n");
    const signature = createHmac("sha256", signingKey(this.config.secretAccessKey, shortDate))
      .update(stringToSign)
      .digest("hex");
    const authorization = `AWS4-HMAC-SHA256 Credential=${this.config.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;

    return fetch(url, {
      method,
      headers: {
        authorization,
        "x-amz-content-sha256": payloadHash,
        "x-amz-date": amzDate,
        ...(body ? { "content-type": "application/octet-stream" } : {}),
      },
      body: body ? new Uint8Array(body) : undefined,
    });
  }

  async put(data: Buffer): Promise<StoredFile> {
    const key = randomUUID();
    const response = await this.request("PUT", key, data);
    if (!response.ok) throw new Error(`R2 upload failed (${response.status}).`);
    return { key, size: data.byteLength };
  }

  async get(key: string): Promise<Buffer> {
    const response = await this.request("GET", key);
    if (!response.ok) throw new Error(`R2 download failed (${response.status}).`);
    return Buffer.from(await response.arrayBuffer());
  }

  async delete(key: string): Promise<void> {
    const response = await this.request("DELETE", key);
    if (!response.ok && response.status !== 404) {
      throw new Error(`R2 delete failed (${response.status}).`);
    }
  }
}
