/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as HospitalsIndexRouteImport } from './routes/hospitals.index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as SpecialtiesSlugRouteImport } from './routes/specialties.$slug'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientReviewsRouteImport } from './routes/patient.reviews'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientFavoritesRouteImport } from './routes/patient.favorites'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as HospitalsIdRouteImport } from './routes/hospitals.$id'
import { Route as HospitalStaffRouteImport } from './routes/hospital.staff'
import { Route as HospitalSettingsRouteImport } from './routes/hospital.settings'
import { Route as HospitalServicesRouteImport } from './routes/hospital.services'
import { Route as HospitalSchedulesRouteImport } from './routes/hospital.schedules'
import { Route as HospitalRoomsBedsRouteImport } from './routes/hospital.rooms-beds'
import { Route as HospitalProfileRouteImport } from './routes/hospital.profile'
import { Route as HospitalPatientsRouteImport } from './routes/hospital.patients'
import { Route as HospitalDoctorsRouteImport } from './routes/hospital.doctors'
import { Route as HospitalDepartmentsRouteImport } from './routes/hospital.departments'
import { Route as HospitalDashboardRouteImport } from './routes/hospital.dashboard'
import { Route as HospitalAppointmentsRouteImport } from './routes/hospital.appointments'
import { Route as HospitalAnalyticsRouteImport } from './routes/hospital.analytics'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorReviewsRouteImport } from './routes/doctor.reviews'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorEarningsRouteImport } from './routes/doctor.earnings'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as DoctorAvailabilityRouteImport } from './routes/doctor.availability'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSpecializationsRouteImport } from './routes/admin.specializations'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as PatientReportsIndexRouteImport } from './routes/patient.reports.index'
import { Route as PatientPrescriptionsIndexRouteImport } from './routes/patient.prescriptions.index'
import { Route as PatientPaymentsIndexRouteImport } from './routes/patient.payments.index'
import { Route as PatientMessagesIndexRouteImport } from './routes/patient.messages.index'
import { Route as PatientMedicalHistoryIndexRouteImport } from './routes/patient.medical-history.index'
import { Route as PatientAppointmentsIndexRouteImport } from './routes/patient.appointments.index'
import { Route as HospitalBillingIndexRouteImport } from './routes/hospital.billing.index'
import { Route as DoctorReportsIndexRouteImport } from './routes/doctor.reports.index'
import { Route as DoctorRecordsIndexRouteImport } from './routes/doctor.records.index'
import { Route as DoctorPrescriptionsIndexRouteImport } from './routes/doctor.prescriptions.index'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as DoctorMessagesIndexRouteImport } from './routes/doctor.messages.index'
import { Route as DoctorAppointmentsIndexRouteImport } from './routes/doctor.appointments.index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminHospitalVerificationIndexRouteImport } from './routes/admin.hospital-verification.index'
import { Route as AdminDoctorVerificationIndexRouteImport } from './routes/admin.doctor-verification.index'
import { Route as PatientReportsIdRouteImport } from './routes/patient.reports.$id'
import { Route as PatientPrescriptionsIdRouteImport } from './routes/patient.prescriptions.$id'
import { Route as PatientPaymentsIdRouteImport } from './routes/patient.payments.$id'
import { Route as PatientMessagesIdRouteImport } from './routes/patient.messages.$id'
import { Route as PatientMedicalHistoryIdRouteImport } from './routes/patient.medical-history.$id'
import { Route as PatientAppointmentsIdRouteImport } from './routes/patient.appointments.$id'
import { Route as HospitalBillingIdRouteImport } from './routes/hospital.billing.$id'
import { Route as DoctorReportsNewRouteImport } from './routes/doctor.reports.new'
import { Route as DoctorReportsIdRouteImport } from './routes/doctor.reports.$id'
import { Route as DoctorRecordsNewRouteImport } from './routes/doctor.records.new'
import { Route as DoctorRecordsIdRouteImport } from './routes/doctor.records.$id'
import { Route as DoctorPrescriptionsNewRouteImport } from './routes/doctor.prescriptions.new'
import { Route as DoctorPrescriptionsIdRouteImport } from './routes/doctor.prescriptions.$id'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor.patients.$id'
import { Route as DoctorMessagesIdRouteImport } from './routes/doctor.messages.$id'
import { Route as DoctorAppointmentsIdRouteImport } from './routes/doctor.appointments.$id'
import { Route as ApiRealtimeStreamRouteImport } from './routes/api.realtime.stream'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin.payments.$id'
import { Route as AdminHospitalVerificationIdRouteImport } from './routes/admin.hospital-verification.$id'
import { Route as AdminDoctorVerificationIdRouteImport } from './routes/admin.doctor-verification.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIndexRoute = HospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesSlugRoute = SpecialtiesSlugRouteImport.update({
  id: '/specialties/$slug',
  path: '/specialties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/patient/settings',
  path: '/patient/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReviewsRoute = PatientReviewsRouteImport.update({
  id: '/patient/reviews',
  path: '/patient/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/patient/notifications',
  path: '/patient/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientFavoritesRoute = PatientFavoritesRouteImport.update({
  id: '/patient/favorites',
  path: '/patient/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsIdRoute = HospitalsIdRouteImport.update({
  id: '/hospitals/$id',
  path: '/hospitals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalStaffRoute = HospitalStaffRouteImport.update({
  id: '/hospital/staff',
  path: '/hospital/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalSettingsRoute = HospitalSettingsRouteImport.update({
  id: '/hospital/settings',
  path: '/hospital/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalServicesRoute = HospitalServicesRouteImport.update({
  id: '/hospital/services',
  path: '/hospital/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalSchedulesRoute = HospitalSchedulesRouteImport.update({
  id: '/hospital/schedules',
  path: '/hospital/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoomsBedsRoute = HospitalRoomsBedsRouteImport.update({
  id: '/hospital/rooms-beds',
  path: '/hospital/rooms-beds',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalProfileRoute = HospitalProfileRouteImport.update({
  id: '/hospital/profile',
  path: '/hospital/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalPatientsRoute = HospitalPatientsRouteImport.update({
  id: '/hospital/patients',
  path: '/hospital/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDoctorsRoute = HospitalDoctorsRouteImport.update({
  id: '/hospital/doctors',
  path: '/hospital/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDepartmentsRoute = HospitalDepartmentsRouteImport.update({
  id: '/hospital/departments',
  path: '/hospital/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital/dashboard',
  path: '/hospital/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAppointmentsRoute = HospitalAppointmentsRouteImport.update({
  id: '/hospital/appointments',
  path: '/hospital/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAnalyticsRoute = HospitalAnalyticsRouteImport.update({
  id: '/hospital/analytics',
  path: '/hospital/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/doctors/$id',
  path: '/doctors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/doctor/settings',
  path: '/doctor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReviewsRoute = DoctorReviewsRouteImport.update({
  id: '/doctor/reviews',
  path: '/doctor/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/doctor/profile',
  path: '/doctor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/doctor/notifications',
  path: '/doctor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorEarningsRoute = DoctorEarningsRouteImport.update({
  id: '/doctor/earnings',
  path: '/doctor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAvailabilityRoute = DoctorAvailabilityRouteImport.update({
  id: '/doctor/availability',
  path: '/doctor/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/doctor/analytics',
  path: '/doctor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpecializationsRoute = AdminSpecializationsRouteImport.update({
  id: '/admin/specializations',
  path: '/admin/specializations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/admin/hospitals',
  path: '/admin/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/admin/activity-logs',
  path: '/admin/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientReportsIndexRoute = PatientReportsIndexRouteImport.update({
  id: '/patient/reports/',
  path: '/patient/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPrescriptionsIndexRoute =
  PatientPrescriptionsIndexRouteImport.update({
    id: '/patient/prescriptions/',
    path: '/patient/prescriptions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientPaymentsIndexRoute = PatientPaymentsIndexRouteImport.update({
  id: '/patient/payments/',
  path: '/patient/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMessagesIndexRoute = PatientMessagesIndexRouteImport.update({
  id: '/patient/messages/',
  path: '/patient/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMedicalHistoryIndexRoute =
  PatientMedicalHistoryIndexRouteImport.update({
    id: '/patient/medical-history/',
    path: '/patient/medical-history/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientAppointmentsIndexRoute =
  PatientAppointmentsIndexRouteImport.update({
    id: '/patient/appointments/',
    path: '/patient/appointments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalBillingIndexRoute = HospitalBillingIndexRouteImport.update({
  id: '/hospital/billing/',
  path: '/hospital/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReportsIndexRoute = DoctorReportsIndexRouteImport.update({
  id: '/doctor/reports/',
  path: '/doctor/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRecordsIndexRoute = DoctorRecordsIndexRouteImport.update({
  id: '/doctor/records/',
  path: '/doctor/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsIndexRoute =
  DoctorPrescriptionsIndexRouteImport.update({
    id: '/doctor/prescriptions/',
    path: '/doctor/prescriptions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/doctor/patients/',
  path: '/doctor/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMessagesIndexRoute = DoctorMessagesIndexRouteImport.update({
  id: '/doctor/messages/',
  path: '/doctor/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsIndexRoute = DoctorAppointmentsIndexRouteImport.update({
  id: '/doctor/appointments/',
  path: '/doctor/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin/payments/',
  path: '/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHospitalVerificationIndexRoute =
  AdminHospitalVerificationIndexRouteImport.update({
    id: '/admin/hospital-verification/',
    path: '/admin/hospital-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDoctorVerificationIndexRoute =
  AdminDoctorVerificationIndexRouteImport.update({
    id: '/admin/doctor-verification/',
    path: '/admin/doctor-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientReportsIdRoute = PatientReportsIdRouteImport.update({
  id: '/patient/reports/$id',
  path: '/patient/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPrescriptionsIdRoute = PatientPrescriptionsIdRouteImport.update({
  id: '/patient/prescriptions/$id',
  path: '/patient/prescriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPaymentsIdRoute = PatientPaymentsIdRouteImport.update({
  id: '/patient/payments/$id',
  path: '/patient/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMessagesIdRoute = PatientMessagesIdRouteImport.update({
  id: '/patient/messages/$id',
  path: '/patient/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientMedicalHistoryIdRoute = PatientMedicalHistoryIdRouteImport.update({
  id: '/patient/medical-history/$id',
  path: '/patient/medical-history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsIdRoute = PatientAppointmentsIdRouteImport.update({
  id: '/patient/appointments/$id',
  path: '/patient/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalBillingIdRoute = HospitalBillingIdRouteImport.update({
  id: '/hospital/billing/$id',
  path: '/hospital/billing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReportsNewRoute = DoctorReportsNewRouteImport.update({
  id: '/doctor/reports/new',
  path: '/doctor/reports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReportsIdRoute = DoctorReportsIdRouteImport.update({
  id: '/doctor/reports/$id',
  path: '/doctor/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRecordsNewRoute = DoctorRecordsNewRouteImport.update({
  id: '/doctor/records/new',
  path: '/doctor/records/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRecordsIdRoute = DoctorRecordsIdRouteImport.update({
  id: '/doctor/records/$id',
  path: '/doctor/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsNewRoute = DoctorPrescriptionsNewRouteImport.update({
  id: '/doctor/prescriptions/new',
  path: '/doctor/prescriptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsIdRoute = DoctorPrescriptionsIdRouteImport.update({
  id: '/doctor/prescriptions/$id',
  path: '/doctor/prescriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/doctor/patients/$id',
  path: '/doctor/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMessagesIdRoute = DoctorMessagesIdRouteImport.update({
  id: '/doctor/messages/$id',
  path: '/doctor/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsIdRoute = DoctorAppointmentsIdRouteImport.update({
  id: '/doctor/appointments/$id',
  path: '/doctor/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeStreamRoute = ApiRealtimeStreamRouteImport.update({
  id: '/api/realtime/stream',
  path: '/api/realtime/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/admin/payments/$id',
  path: '/admin/payments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHospitalVerificationIdRoute =
  AdminHospitalVerificationIdRouteImport.update({
    id: '/admin/hospital-verification/$id',
    path: '/admin/hospital-verification/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDoctorVerificationIdRoute =
  AdminDoctorVerificationIdRouteImport.update({
    id: '/admin/doctor-verification/$id',
    path: '/admin/doctor-verification/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specializations': typeof AdminSpecializationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/appointments': typeof HospitalAppointmentsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/departments': typeof HospitalDepartmentsRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/rooms-beds': typeof HospitalRoomsBedsRoute
  '/hospital/schedules': typeof HospitalSchedulesRoute
  '/hospital/services': typeof HospitalServicesRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/hospitals/$id': typeof HospitalsIdRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/reviews': typeof PatientReviewsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/admin/doctor-verification/$id': typeof AdminDoctorVerificationIdRoute
  '/admin/hospital-verification/$id': typeof AdminHospitalVerificationIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/api/realtime/stream': typeof ApiRealtimeStreamRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/doctor/messages/$id': typeof DoctorMessagesIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/prescriptions/$id': typeof DoctorPrescriptionsIdRoute
  '/doctor/prescriptions/new': typeof DoctorPrescriptionsNewRoute
  '/doctor/records/$id': typeof DoctorRecordsIdRoute
  '/doctor/records/new': typeof DoctorRecordsNewRoute
  '/doctor/reports/$id': typeof DoctorReportsIdRoute
  '/doctor/reports/new': typeof DoctorReportsNewRoute
  '/hospital/billing/$id': typeof HospitalBillingIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/medical-history/$id': typeof PatientMedicalHistoryIdRoute
  '/patient/messages/$id': typeof PatientMessagesIdRoute
  '/patient/payments/$id': typeof PatientPaymentsIdRoute
  '/patient/prescriptions/$id': typeof PatientPrescriptionsIdRoute
  '/patient/reports/$id': typeof PatientReportsIdRoute
  '/admin/doctor-verification/': typeof AdminDoctorVerificationIndexRoute
  '/admin/hospital-verification/': typeof AdminHospitalVerificationIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/doctor/appointments/': typeof DoctorAppointmentsIndexRoute
  '/doctor/messages/': typeof DoctorMessagesIndexRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/doctor/prescriptions/': typeof DoctorPrescriptionsIndexRoute
  '/doctor/records/': typeof DoctorRecordsIndexRoute
  '/doctor/reports/': typeof DoctorReportsIndexRoute
  '/hospital/billing/': typeof HospitalBillingIndexRoute
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patient/medical-history/': typeof PatientMedicalHistoryIndexRoute
  '/patient/messages/': typeof PatientMessagesIndexRoute
  '/patient/payments/': typeof PatientPaymentsIndexRoute
  '/patient/prescriptions/': typeof PatientPrescriptionsIndexRoute
  '/patient/reports/': typeof PatientReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specializations': typeof AdminSpecializationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/appointments': typeof HospitalAppointmentsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/departments': typeof HospitalDepartmentsRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/rooms-beds': typeof HospitalRoomsBedsRoute
  '/hospital/schedules': typeof HospitalSchedulesRoute
  '/hospital/services': typeof HospitalServicesRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/hospitals/$id': typeof HospitalsIdRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/reviews': typeof PatientReviewsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/doctors': typeof DoctorsIndexRoute
  '/hospitals': typeof HospitalsIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
  '/admin/doctor-verification/$id': typeof AdminDoctorVerificationIdRoute
  '/admin/hospital-verification/$id': typeof AdminHospitalVerificationIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/api/realtime/stream': typeof ApiRealtimeStreamRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/doctor/messages/$id': typeof DoctorMessagesIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/prescriptions/$id': typeof DoctorPrescriptionsIdRoute
  '/doctor/prescriptions/new': typeof DoctorPrescriptionsNewRoute
  '/doctor/records/$id': typeof DoctorRecordsIdRoute
  '/doctor/records/new': typeof DoctorRecordsNewRoute
  '/doctor/reports/$id': typeof DoctorReportsIdRoute
  '/doctor/reports/new': typeof DoctorReportsNewRoute
  '/hospital/billing/$id': typeof HospitalBillingIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/medical-history/$id': typeof PatientMedicalHistoryIdRoute
  '/patient/messages/$id': typeof PatientMessagesIdRoute
  '/patient/payments/$id': typeof PatientPaymentsIdRoute
  '/patient/prescriptions/$id': typeof PatientPrescriptionsIdRoute
  '/patient/reports/$id': typeof PatientReportsIdRoute
  '/admin/doctor-verification': typeof AdminDoctorVerificationIndexRoute
  '/admin/hospital-verification': typeof AdminHospitalVerificationIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/doctor/appointments': typeof DoctorAppointmentsIndexRoute
  '/doctor/messages': typeof DoctorMessagesIndexRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsIndexRoute
  '/doctor/records': typeof DoctorRecordsIndexRoute
  '/doctor/reports': typeof DoctorReportsIndexRoute
  '/hospital/billing': typeof HospitalBillingIndexRoute
  '/patient/appointments': typeof PatientAppointmentsIndexRoute
  '/patient/medical-history': typeof PatientMedicalHistoryIndexRoute
  '/patient/messages': typeof PatientMessagesIndexRoute
  '/patient/payments': typeof PatientPaymentsIndexRoute
  '/patient/prescriptions': typeof PatientPrescriptionsIndexRoute
  '/patient/reports': typeof PatientReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specializations': typeof AdminSpecializationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/availability': typeof DoctorAvailabilityRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reviews': typeof DoctorReviewsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/hospital/analytics': typeof HospitalAnalyticsRoute
  '/hospital/appointments': typeof HospitalAppointmentsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/departments': typeof HospitalDepartmentsRoute
  '/hospital/doctors': typeof HospitalDoctorsRoute
  '/hospital/patients': typeof HospitalPatientsRoute
  '/hospital/profile': typeof HospitalProfileRoute
  '/hospital/rooms-beds': typeof HospitalRoomsBedsRoute
  '/hospital/schedules': typeof HospitalSchedulesRoute
  '/hospital/services': typeof HospitalServicesRoute
  '/hospital/settings': typeof HospitalSettingsRoute
  '/hospital/staff': typeof HospitalStaffRoute
  '/hospitals/$id': typeof HospitalsIdRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/reviews': typeof PatientReviewsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/specialties/$slug': typeof SpecialtiesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/hospitals/': typeof HospitalsIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
  '/admin/doctor-verification/$id': typeof AdminDoctorVerificationIdRoute
  '/admin/hospital-verification/$id': typeof AdminHospitalVerificationIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/api/realtime/stream': typeof ApiRealtimeStreamRoute
  '/doctor/appointments/$id': typeof DoctorAppointmentsIdRoute
  '/doctor/messages/$id': typeof DoctorMessagesIdRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/prescriptions/$id': typeof DoctorPrescriptionsIdRoute
  '/doctor/prescriptions/new': typeof DoctorPrescriptionsNewRoute
  '/doctor/records/$id': typeof DoctorRecordsIdRoute
  '/doctor/records/new': typeof DoctorRecordsNewRoute
  '/doctor/reports/$id': typeof DoctorReportsIdRoute
  '/doctor/reports/new': typeof DoctorReportsNewRoute
  '/hospital/billing/$id': typeof HospitalBillingIdRoute
  '/patient/appointments/$id': typeof PatientAppointmentsIdRoute
  '/patient/medical-history/$id': typeof PatientMedicalHistoryIdRoute
  '/patient/messages/$id': typeof PatientMessagesIdRoute
  '/patient/payments/$id': typeof PatientPaymentsIdRoute
  '/patient/prescriptions/$id': typeof PatientPrescriptionsIdRoute
  '/patient/reports/$id': typeof PatientReportsIdRoute
  '/admin/doctor-verification/': typeof AdminDoctorVerificationIndexRoute
  '/admin/hospital-verification/': typeof AdminHospitalVerificationIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/doctor/appointments/': typeof DoctorAppointmentsIndexRoute
  '/doctor/messages/': typeof DoctorMessagesIndexRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
  '/doctor/prescriptions/': typeof DoctorPrescriptionsIndexRoute
  '/doctor/records/': typeof DoctorRecordsIndexRoute
  '/doctor/reports/': typeof DoctorReportsIndexRoute
  '/hospital/billing/': typeof HospitalBillingIndexRoute
  '/patient/appointments/': typeof PatientAppointmentsIndexRoute
  '/patient/medical-history/': typeof PatientMedicalHistoryIndexRoute
  '/patient/messages/': typeof PatientMessagesIndexRoute
  '/patient/payments/': typeof PatientPaymentsIndexRoute
  '/patient/prescriptions/': typeof PatientPrescriptionsIndexRoute
  '/patient/reports/': typeof PatientReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/admin/activity-logs'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/specializations'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/articles/$id'
    | '/doctor/analytics'
    | '/doctor/availability'
    | '/doctor/dashboard'
    | '/doctor/earnings'
    | '/doctor/notifications'
    | '/doctor/profile'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/hospital/analytics'
    | '/hospital/appointments'
    | '/hospital/dashboard'
    | '/hospital/departments'
    | '/hospital/doctors'
    | '/hospital/patients'
    | '/hospital/profile'
    | '/hospital/rooms-beds'
    | '/hospital/schedules'
    | '/hospital/services'
    | '/hospital/settings'
    | '/hospital/staff'
    | '/hospitals/$id'
    | '/patient/dashboard'
    | '/patient/favorites'
    | '/patient/notifications'
    | '/patient/reviews'
    | '/patient/settings'
    | '/specialties/$slug'
    | '/articles/'
    | '/doctors/'
    | '/hospitals/'
    | '/specialties/'
    | '/admin/doctor-verification/$id'
    | '/admin/hospital-verification/$id'
    | '/admin/payments/$id'
    | '/api/realtime/stream'
    | '/doctor/appointments/$id'
    | '/doctor/messages/$id'
    | '/doctor/patients/$id'
    | '/doctor/prescriptions/$id'
    | '/doctor/prescriptions/new'
    | '/doctor/records/$id'
    | '/doctor/records/new'
    | '/doctor/reports/$id'
    | '/doctor/reports/new'
    | '/hospital/billing/$id'
    | '/patient/appointments/$id'
    | '/patient/medical-history/$id'
    | '/patient/messages/$id'
    | '/patient/payments/$id'
    | '/patient/prescriptions/$id'
    | '/patient/reports/$id'
    | '/admin/doctor-verification/'
    | '/admin/hospital-verification/'
    | '/admin/payments/'
    | '/doctor/appointments/'
    | '/doctor/messages/'
    | '/doctor/patients/'
    | '/doctor/prescriptions/'
    | '/doctor/records/'
    | '/doctor/reports/'
    | '/hospital/billing/'
    | '/patient/appointments/'
    | '/patient/medical-history/'
    | '/patient/messages/'
    | '/patient/payments/'
    | '/patient/prescriptions/'
    | '/patient/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/admin/activity-logs'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/specializations'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/articles/$id'
    | '/doctor/analytics'
    | '/doctor/availability'
    | '/doctor/dashboard'
    | '/doctor/earnings'
    | '/doctor/notifications'
    | '/doctor/profile'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/hospital/analytics'
    | '/hospital/appointments'
    | '/hospital/dashboard'
    | '/hospital/departments'
    | '/hospital/doctors'
    | '/hospital/patients'
    | '/hospital/profile'
    | '/hospital/rooms-beds'
    | '/hospital/schedules'
    | '/hospital/services'
    | '/hospital/settings'
    | '/hospital/staff'
    | '/hospitals/$id'
    | '/patient/dashboard'
    | '/patient/favorites'
    | '/patient/notifications'
    | '/patient/reviews'
    | '/patient/settings'
    | '/specialties/$slug'
    | '/articles'
    | '/doctors'
    | '/hospitals'
    | '/specialties'
    | '/admin/doctor-verification/$id'
    | '/admin/hospital-verification/$id'
    | '/admin/payments/$id'
    | '/api/realtime/stream'
    | '/doctor/appointments/$id'
    | '/doctor/messages/$id'
    | '/doctor/patients/$id'
    | '/doctor/prescriptions/$id'
    | '/doctor/prescriptions/new'
    | '/doctor/records/$id'
    | '/doctor/records/new'
    | '/doctor/reports/$id'
    | '/doctor/reports/new'
    | '/hospital/billing/$id'
    | '/patient/appointments/$id'
    | '/patient/medical-history/$id'
    | '/patient/messages/$id'
    | '/patient/payments/$id'
    | '/patient/prescriptions/$id'
    | '/patient/reports/$id'
    | '/admin/doctor-verification'
    | '/admin/hospital-verification'
    | '/admin/payments'
    | '/doctor/appointments'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/records'
    | '/doctor/reports'
    | '/hospital/billing'
    | '/patient/appointments'
    | '/patient/medical-history'
    | '/patient/messages'
    | '/patient/payments'
    | '/patient/prescriptions'
    | '/patient/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/unauthorized'
    | '/admin/activity-logs'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/doctors'
    | '/admin/hospitals'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/specializations'
    | '/admin/users'
    | '/api/health'
    | '/api/ready'
    | '/articles/$id'
    | '/doctor/analytics'
    | '/doctor/availability'
    | '/doctor/dashboard'
    | '/doctor/earnings'
    | '/doctor/notifications'
    | '/doctor/profile'
    | '/doctor/reviews'
    | '/doctor/settings'
    | '/doctors/$id'
    | '/hospital/analytics'
    | '/hospital/appointments'
    | '/hospital/dashboard'
    | '/hospital/departments'
    | '/hospital/doctors'
    | '/hospital/patients'
    | '/hospital/profile'
    | '/hospital/rooms-beds'
    | '/hospital/schedules'
    | '/hospital/services'
    | '/hospital/settings'
    | '/hospital/staff'
    | '/hospitals/$id'
    | '/patient/dashboard'
    | '/patient/favorites'
    | '/patient/notifications'
    | '/patient/reviews'
    | '/patient/settings'
    | '/specialties/$slug'
    | '/articles/'
    | '/doctors/'
    | '/hospitals/'
    | '/specialties/'
    | '/admin/doctor-verification/$id'
    | '/admin/hospital-verification/$id'
    | '/admin/payments/$id'
    | '/api/realtime/stream'
    | '/doctor/appointments/$id'
    | '/doctor/messages/$id'
    | '/doctor/patients/$id'
    | '/doctor/prescriptions/$id'
    | '/doctor/prescriptions/new'
    | '/doctor/records/$id'
    | '/doctor/records/new'
    | '/doctor/reports/$id'
    | '/doctor/reports/new'
    | '/hospital/billing/$id'
    | '/patient/appointments/$id'
    | '/patient/medical-history/$id'
    | '/patient/messages/$id'
    | '/patient/payments/$id'
    | '/patient/prescriptions/$id'
    | '/patient/reports/$id'
    | '/admin/doctor-verification/'
    | '/admin/hospital-verification/'
    | '/admin/payments/'
    | '/doctor/appointments/'
    | '/doctor/messages/'
    | '/doctor/patients/'
    | '/doctor/prescriptions/'
    | '/doctor/records/'
    | '/doctor/reports/'
    | '/hospital/billing/'
    | '/patient/appointments/'
    | '/patient/medical-history/'
    | '/patient/messages/'
    | '/patient/payments/'
    | '/patient/prescriptions/'
    | '/patient/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpecializationsRoute: typeof AdminSpecializationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorAvailabilityRoute: typeof DoctorAvailabilityRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorEarningsRoute: typeof DoctorEarningsRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorReviewsRoute: typeof DoctorReviewsRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorsIdRoute: typeof DoctorsIdRoute
  HospitalAnalyticsRoute: typeof HospitalAnalyticsRoute
  HospitalAppointmentsRoute: typeof HospitalAppointmentsRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  HospitalDepartmentsRoute: typeof HospitalDepartmentsRoute
  HospitalDoctorsRoute: typeof HospitalDoctorsRoute
  HospitalPatientsRoute: typeof HospitalPatientsRoute
  HospitalProfileRoute: typeof HospitalProfileRoute
  HospitalRoomsBedsRoute: typeof HospitalRoomsBedsRoute
  HospitalSchedulesRoute: typeof HospitalSchedulesRoute
  HospitalServicesRoute: typeof HospitalServicesRoute
  HospitalSettingsRoute: typeof HospitalSettingsRoute
  HospitalStaffRoute: typeof HospitalStaffRoute
  HospitalsIdRoute: typeof HospitalsIdRoute
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientFavoritesRoute: typeof PatientFavoritesRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientReviewsRoute: typeof PatientReviewsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  SpecialtiesSlugRoute: typeof SpecialtiesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  HospitalsIndexRoute: typeof HospitalsIndexRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
  AdminDoctorVerificationIdRoute: typeof AdminDoctorVerificationIdRoute
  AdminHospitalVerificationIdRoute: typeof AdminHospitalVerificationIdRoute
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
  ApiRealtimeStreamRoute: typeof ApiRealtimeStreamRoute
  DoctorAppointmentsIdRoute: typeof DoctorAppointmentsIdRoute
  DoctorMessagesIdRoute: typeof DoctorMessagesIdRoute
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
  DoctorPrescriptionsIdRoute: typeof DoctorPrescriptionsIdRoute
  DoctorPrescriptionsNewRoute: typeof DoctorPrescriptionsNewRoute
  DoctorRecordsIdRoute: typeof DoctorRecordsIdRoute
  DoctorRecordsNewRoute: typeof DoctorRecordsNewRoute
  DoctorReportsIdRoute: typeof DoctorReportsIdRoute
  DoctorReportsNewRoute: typeof DoctorReportsNewRoute
  HospitalBillingIdRoute: typeof HospitalBillingIdRoute
  PatientAppointmentsIdRoute: typeof PatientAppointmentsIdRoute
  PatientMedicalHistoryIdRoute: typeof PatientMedicalHistoryIdRoute
  PatientMessagesIdRoute: typeof PatientMessagesIdRoute
  PatientPaymentsIdRoute: typeof PatientPaymentsIdRoute
  PatientPrescriptionsIdRoute: typeof PatientPrescriptionsIdRoute
  PatientReportsIdRoute: typeof PatientReportsIdRoute
  AdminDoctorVerificationIndexRoute: typeof AdminDoctorVerificationIndexRoute
  AdminHospitalVerificationIndexRoute: typeof AdminHospitalVerificationIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  DoctorAppointmentsIndexRoute: typeof DoctorAppointmentsIndexRoute
  DoctorMessagesIndexRoute: typeof DoctorMessagesIndexRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
  DoctorPrescriptionsIndexRoute: typeof DoctorPrescriptionsIndexRoute
  DoctorRecordsIndexRoute: typeof DoctorRecordsIndexRoute
  DoctorReportsIndexRoute: typeof DoctorReportsIndexRoute
  HospitalBillingIndexRoute: typeof HospitalBillingIndexRoute
  PatientAppointmentsIndexRoute: typeof PatientAppointmentsIndexRoute
  PatientMedicalHistoryIndexRoute: typeof PatientMedicalHistoryIndexRoute
  PatientMessagesIndexRoute: typeof PatientMessagesIndexRoute
  PatientPaymentsIndexRoute: typeof PatientPaymentsIndexRoute
  PatientPrescriptionsIndexRoute: typeof PatientPrescriptionsIndexRoute
  PatientReportsIndexRoute: typeof PatientReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/specialties'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/': {
      id: '/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof HospitalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/$slug': {
      id: '/specialties/$slug'
      path: '/specialties/$slug'
      fullPath: '/specialties/$slug'
      preLoaderRoute: typeof SpecialtiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/patient/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reviews': {
      id: '/patient/reviews'
      path: '/patient/reviews'
      fullPath: '/patient/reviews'
      preLoaderRoute: typeof PatientReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/patient/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/favorites': {
      id: '/patient/favorites'
      path: '/patient/favorites'
      fullPath: '/patient/favorites'
      preLoaderRoute: typeof PatientFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$id': {
      id: '/hospitals/$id'
      path: '/hospitals/$id'
      fullPath: '/hospitals/$id'
      preLoaderRoute: typeof HospitalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/staff': {
      id: '/hospital/staff'
      path: '/hospital/staff'
      fullPath: '/hospital/staff'
      preLoaderRoute: typeof HospitalStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/settings': {
      id: '/hospital/settings'
      path: '/hospital/settings'
      fullPath: '/hospital/settings'
      preLoaderRoute: typeof HospitalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/services': {
      id: '/hospital/services'
      path: '/hospital/services'
      fullPath: '/hospital/services'
      preLoaderRoute: typeof HospitalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/schedules': {
      id: '/hospital/schedules'
      path: '/hospital/schedules'
      fullPath: '/hospital/schedules'
      preLoaderRoute: typeof HospitalSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/rooms-beds': {
      id: '/hospital/rooms-beds'
      path: '/hospital/rooms-beds'
      fullPath: '/hospital/rooms-beds'
      preLoaderRoute: typeof HospitalRoomsBedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/profile': {
      id: '/hospital/profile'
      path: '/hospital/profile'
      fullPath: '/hospital/profile'
      preLoaderRoute: typeof HospitalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/patients': {
      id: '/hospital/patients'
      path: '/hospital/patients'
      fullPath: '/hospital/patients'
      preLoaderRoute: typeof HospitalPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/doctors': {
      id: '/hospital/doctors'
      path: '/hospital/doctors'
      fullPath: '/hospital/doctors'
      preLoaderRoute: typeof HospitalDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/departments': {
      id: '/hospital/departments'
      path: '/hospital/departments'
      fullPath: '/hospital/departments'
      preLoaderRoute: typeof HospitalDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/dashboard': {
      id: '/hospital/dashboard'
      path: '/hospital/dashboard'
      fullPath: '/hospital/dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/appointments': {
      id: '/hospital/appointments'
      path: '/hospital/appointments'
      fullPath: '/hospital/appointments'
      preLoaderRoute: typeof HospitalAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/analytics': {
      id: '/hospital/analytics'
      path: '/hospital/analytics'
      fullPath: '/hospital/analytics'
      preLoaderRoute: typeof HospitalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/doctors/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reviews': {
      id: '/doctor/reviews'
      path: '/doctor/reviews'
      fullPath: '/doctor/reviews'
      preLoaderRoute: typeof DoctorReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/doctor/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/earnings': {
      id: '/doctor/earnings'
      path: '/doctor/earnings'
      fullPath: '/doctor/earnings'
      preLoaderRoute: typeof DoctorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/availability': {
      id: '/doctor/availability'
      path: '/doctor/availability'
      fullPath: '/doctor/availability'
      preLoaderRoute: typeof DoctorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/doctor/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/specializations': {
      id: '/admin/specializations'
      path: '/admin/specializations'
      fullPath: '/admin/specializations'
      preLoaderRoute: typeof AdminSpecializationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/admin/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/admin/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports/': {
      id: '/patient/reports/'
      path: '/patient/reports'
      fullPath: '/patient/reports/'
      preLoaderRoute: typeof PatientReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/prescriptions/': {
      id: '/patient/prescriptions/'
      path: '/patient/prescriptions'
      fullPath: '/patient/prescriptions/'
      preLoaderRoute: typeof PatientPrescriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/payments/': {
      id: '/patient/payments/'
      path: '/patient/payments'
      fullPath: '/patient/payments/'
      preLoaderRoute: typeof PatientPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/messages/': {
      id: '/patient/messages/'
      path: '/patient/messages'
      fullPath: '/patient/messages/'
      preLoaderRoute: typeof PatientMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/medical-history/': {
      id: '/patient/medical-history/'
      path: '/patient/medical-history'
      fullPath: '/patient/medical-history/'
      preLoaderRoute: typeof PatientMedicalHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments/': {
      id: '/patient/appointments/'
      path: '/patient/appointments'
      fullPath: '/patient/appointments/'
      preLoaderRoute: typeof PatientAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/billing/': {
      id: '/hospital/billing/'
      path: '/hospital/billing'
      fullPath: '/hospital/billing/'
      preLoaderRoute: typeof HospitalBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reports/': {
      id: '/doctor/reports/'
      path: '/doctor/reports'
      fullPath: '/doctor/reports/'
      preLoaderRoute: typeof DoctorReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/records/': {
      id: '/doctor/records/'
      path: '/doctor/records'
      fullPath: '/doctor/records/'
      preLoaderRoute: typeof DoctorRecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions/': {
      id: '/doctor/prescriptions/'
      path: '/doctor/prescriptions'
      fullPath: '/doctor/prescriptions/'
      preLoaderRoute: typeof DoctorPrescriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/messages/': {
      id: '/doctor/messages/'
      path: '/doctor/messages'
      fullPath: '/doctor/messages/'
      preLoaderRoute: typeof DoctorMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments/': {
      id: '/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments/'
      preLoaderRoute: typeof DoctorAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/admin/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hospital-verification/': {
      id: '/admin/hospital-verification/'
      path: '/admin/hospital-verification'
      fullPath: '/admin/hospital-verification/'
      preLoaderRoute: typeof AdminHospitalVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctor-verification/': {
      id: '/admin/doctor-verification/'
      path: '/admin/doctor-verification'
      fullPath: '/admin/doctor-verification/'
      preLoaderRoute: typeof AdminDoctorVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/reports/$id': {
      id: '/patient/reports/$id'
      path: '/patient/reports/$id'
      fullPath: '/patient/reports/$id'
      preLoaderRoute: typeof PatientReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/prescriptions/$id': {
      id: '/patient/prescriptions/$id'
      path: '/patient/prescriptions/$id'
      fullPath: '/patient/prescriptions/$id'
      preLoaderRoute: typeof PatientPrescriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/payments/$id': {
      id: '/patient/payments/$id'
      path: '/patient/payments/$id'
      fullPath: '/patient/payments/$id'
      preLoaderRoute: typeof PatientPaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/messages/$id': {
      id: '/patient/messages/$id'
      path: '/patient/messages/$id'
      fullPath: '/patient/messages/$id'
      preLoaderRoute: typeof PatientMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/medical-history/$id': {
      id: '/patient/medical-history/$id'
      path: '/patient/medical-history/$id'
      fullPath: '/patient/medical-history/$id'
      preLoaderRoute: typeof PatientMedicalHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments/$id': {
      id: '/patient/appointments/$id'
      path: '/patient/appointments/$id'
      fullPath: '/patient/appointments/$id'
      preLoaderRoute: typeof PatientAppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/billing/$id': {
      id: '/hospital/billing/$id'
      path: '/hospital/billing/$id'
      fullPath: '/hospital/billing/$id'
      preLoaderRoute: typeof HospitalBillingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reports/new': {
      id: '/doctor/reports/new'
      path: '/doctor/reports/new'
      fullPath: '/doctor/reports/new'
      preLoaderRoute: typeof DoctorReportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reports/$id': {
      id: '/doctor/reports/$id'
      path: '/doctor/reports/$id'
      fullPath: '/doctor/reports/$id'
      preLoaderRoute: typeof DoctorReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/records/new': {
      id: '/doctor/records/new'
      path: '/doctor/records/new'
      fullPath: '/doctor/records/new'
      preLoaderRoute: typeof DoctorRecordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/records/$id': {
      id: '/doctor/records/$id'
      path: '/doctor/records/$id'
      fullPath: '/doctor/records/$id'
      preLoaderRoute: typeof DoctorRecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions/new': {
      id: '/doctor/prescriptions/new'
      path: '/doctor/prescriptions/new'
      fullPath: '/doctor/prescriptions/new'
      preLoaderRoute: typeof DoctorPrescriptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions/$id': {
      id: '/doctor/prescriptions/$id'
      path: '/doctor/prescriptions/$id'
      fullPath: '/doctor/prescriptions/$id'
      preLoaderRoute: typeof DoctorPrescriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/doctor/patients/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/messages/$id': {
      id: '/doctor/messages/$id'
      path: '/doctor/messages/$id'
      fullPath: '/doctor/messages/$id'
      preLoaderRoute: typeof DoctorMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments/$id': {
      id: '/doctor/appointments/$id'
      path: '/doctor/appointments/$id'
      fullPath: '/doctor/appointments/$id'
      preLoaderRoute: typeof DoctorAppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/stream': {
      id: '/api/realtime/stream'
      path: '/api/realtime/stream'
      fullPath: '/api/realtime/stream'
      preLoaderRoute: typeof ApiRealtimeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/admin/payments/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hospital-verification/$id': {
      id: '/admin/hospital-verification/$id'
      path: '/admin/hospital-verification/$id'
      fullPath: '/admin/hospital-verification/$id'
      preLoaderRoute: typeof AdminHospitalVerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctor-verification/$id': {
      id: '/admin/doctor-verification/$id'
      path: '/admin/doctor-verification/$id'
      fullPath: '/admin/doctor-verification/$id'
      preLoaderRoute: typeof AdminDoctorVerificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpecializationsRoute: AdminSpecializationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorAvailabilityRoute: DoctorAvailabilityRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorEarningsRoute: DoctorEarningsRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorReviewsRoute: DoctorReviewsRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorsIdRoute: DoctorsIdRoute,
  HospitalAnalyticsRoute: HospitalAnalyticsRoute,
  HospitalAppointmentsRoute: HospitalAppointmentsRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  HospitalDepartmentsRoute: HospitalDepartmentsRoute,
  HospitalDoctorsRoute: HospitalDoctorsRoute,
  HospitalPatientsRoute: HospitalPatientsRoute,
  HospitalProfileRoute: HospitalProfileRoute,
  HospitalRoomsBedsRoute: HospitalRoomsBedsRoute,
  HospitalSchedulesRoute: HospitalSchedulesRoute,
  HospitalServicesRoute: HospitalServicesRoute,
  HospitalSettingsRoute: HospitalSettingsRoute,
  HospitalStaffRoute: HospitalStaffRoute,
  HospitalsIdRoute: HospitalsIdRoute,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientFavoritesRoute: PatientFavoritesRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientReviewsRoute: PatientReviewsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  SpecialtiesSlugRoute: SpecialtiesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  HospitalsIndexRoute: HospitalsIndexRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
  AdminDoctorVerificationIdRoute: AdminDoctorVerificationIdRoute,
  AdminHospitalVerificationIdRoute: AdminHospitalVerificationIdRoute,
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
  ApiRealtimeStreamRoute: ApiRealtimeStreamRoute,
  DoctorAppointmentsIdRoute: DoctorAppointmentsIdRoute,
  DoctorMessagesIdRoute: DoctorMessagesIdRoute,
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
  DoctorPrescriptionsIdRoute: DoctorPrescriptionsIdRoute,
  DoctorPrescriptionsNewRoute: DoctorPrescriptionsNewRoute,
  DoctorRecordsIdRoute: DoctorRecordsIdRoute,
  DoctorRecordsNewRoute: DoctorRecordsNewRoute,
  DoctorReportsIdRoute: DoctorReportsIdRoute,
  DoctorReportsNewRoute: DoctorReportsNewRoute,
  HospitalBillingIdRoute: HospitalBillingIdRoute,
  PatientAppointmentsIdRoute: PatientAppointmentsIdRoute,
  PatientMedicalHistoryIdRoute: PatientMedicalHistoryIdRoute,
  PatientMessagesIdRoute: PatientMessagesIdRoute,
  PatientPaymentsIdRoute: PatientPaymentsIdRoute,
  PatientPrescriptionsIdRoute: PatientPrescriptionsIdRoute,
  PatientReportsIdRoute: PatientReportsIdRoute,
  AdminDoctorVerificationIndexRoute: AdminDoctorVerificationIndexRoute,
  AdminHospitalVerificationIndexRoute: AdminHospitalVerificationIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  DoctorAppointmentsIndexRoute: DoctorAppointmentsIndexRoute,
  DoctorMessagesIndexRoute: DoctorMessagesIndexRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
  DoctorPrescriptionsIndexRoute: DoctorPrescriptionsIndexRoute,
  DoctorRecordsIndexRoute: DoctorRecordsIndexRoute,
  DoctorReportsIndexRoute: DoctorReportsIndexRoute,
  HospitalBillingIndexRoute: HospitalBillingIndexRoute,
  PatientAppointmentsIndexRoute: PatientAppointmentsIndexRoute,
  PatientMedicalHistoryIndexRoute: PatientMedicalHistoryIndexRoute,
  PatientMessagesIndexRoute: PatientMessagesIndexRoute,
  PatientPaymentsIndexRoute: PatientPaymentsIndexRoute,
  PatientPrescriptionsIndexRoute: PatientPrescriptionsIndexRoute,
  PatientReportsIndexRoute: PatientReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
